// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
static struct leds s_leds = {false, false, 42};
void glue_get_leds(struct leds *data) {
  *data = s_leds;  // Sync with your device
}
void glue_set_leds(struct leds *data) {
  s_leds = *data; // Sync with your device
}

void *glue_ota_begin_firmware_update(char *file_name, size_t total_size) {
  bool ok = mg_ota_begin(total_size);
  MG_DEBUG(("%s size %lu, ok: %d", file_name, total_size, ok));
  return ok ? (void *) 1 : NULL;
}
bool glue_ota_end_firmware_update(void *context) {
  mg_timer_add(&g_mgr, 500, 0, (void (*)(void *)) (void *) mg_ota_end, context);
  return true;
}
bool glue_ota_write_firmware_update(void *context, void *buf, size_t len) {
  MG_DEBUG(("ctx: %p %p/%lu", context, buf, len));
  return mg_ota_write(buf, len);
}

static uint64_t s_action_timeout_save_event;  // Time when save_event ends
bool glue_check_save_event(void) {
  return s_action_timeout_save_event > mg_now(); // Return true if save_event is in progress
}
void glue_start_save_event(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_save_event = mg_now() + 1000; // Start save_event, finish after 1 second
}

void glue_reply_events(struct mg_connection *c, struct mg_http_message *hm) {
  const char *headers = "Cache-Control: no-cache\r\n" "Content-Type: application/json\r\n";
  const char *value = "[{\"id\":0,\"timestamp\":12345,\"message\":\"Something failed\",\"priority\":2,\"status\":\"active\",\"notes\":\"some notes\"},{\"id\":1,\"timestamp\":12395,\"message\":\"Something succeeded\",\"priority\":1,\"status\":\"processed\",\"notes\":\"\"}]";
  (void) hm;
  mg_http_reply(c, 200, headers, "%s\n", value);
}